package com.myproject.library_app;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.myproject.library_app.LibraryBook;
import com.myproject.library_app.LibraryBookRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/libapp") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private LibraryBookRepository libraryBookRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewLibraryBook (@RequestParam String name
            , @RequestParam String author, @RequestParam String publisher, @RequestParam String subject) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        LibraryBook n = new LibraryBook();
        n.setName(name);
        n.setAuthor(author);                       //author
        n.setPublisher(publisher);
        n.setSubject(subject);

        libraryBookRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<LibraryBook> getAllLibraryBooks() {
        // This returns a JSON or XML with the users
        return libraryBookRepository.findAll();
    }
}
